### ISSUE TITLE
Movie Lens Dataset

### ISSUE THREAD

**Issue by mayukhdas** [trangptm/Column_networks#2]
Dear Authors

The movie lens latest data set using for experiments in the publication (and provided in this repo) has been scrubbed of all the identifiers (such as title and id). Do you still have the original data set. 

The data available on Grouplens has since been updated and hence the rows do not align. 

Thanks in advance for the help
-- Mayukh

**Comment by trangptm** [comment]
Hi Mayukh,
Please find the raw dataset I used in the link below:
https://drive.google.com/open?id=1zZsbRTrcwz6Makx2XR1-TentUgE5osPy
Hope this helps

**Comment by mayukhdas** [comment]
Hi Trang,

Thanks a lot for the help.

-- Mayukh

**Comment by mayukhdas** [comment]
Hi Trang,

Apologies for the trouble, but do you also have the plot summaries that the paper says was extracted from IMDB for the movies in the data set? It will be of great help.

Thanks
-- Mayukh

**Comment by trangptm** [comment]
I do not keep the raw plot summaries anymore but you can find them on IMDB database.

**Comment by mayukhdas** [comment]
Okay, thanks a lot for your help. 
Really appreciate it. 

-- Mayukh
